---
title: "Sorting dictionary keys"
date: "`r format(Sys.time(), '%d %B %Y')`"
author: Ben Bolker
output:
  tufte_handout:
     pandoc_args: ["--dpi", "300"]
---

</style>
<!--    content: url(https://i.creativecommons.org/l/by-sa/4.0/88x31.png)
>
<!-- Limit image width and height -->
<style type="text/css">
img {     
  max-height: 560px;     
  max-width: 800px; 
}
</style>

```{r opts,message=FALSE,echo=FALSE}
library("knitr")
library("reticulate")
knitr::knit_engines$set(python = reticulate::eng_python)
use_python("/usr/bin/python3")
```

I was interested in figuring out a way of producing a list of the keys of a dictionary, sorted in the order of its values. This is a little harder than it sounds; if you extract keys and values separately (`d.keys()`, `d.values()`), you have no guarantee that they're in matching order.

The other challenge is that I'd like a solution that would work for relatively **novice** Python users, e.g.: no comprehensions, `lambda` expressions, etc.. The most efficient/Pythonic solutions typically use things like the `dict.get` method or the `operator.itemgetter` function - too magical for my intended audience.

Here are some of the leading [StackOverflow solutions](https://stackoverflow.com/questions/613183/how-do-i-sort-a-dictionary-by-value/613218#613218), most of which use `sorted()` with its optional `key` argument, and are too "magic": there are also some solutions [here](https://thispointer.com/python-how-to-sort-a-dictionary-by-key-or-value/)

1. lambda expressions:

```{python}
d = {"a": 2, "c": 4, "b": 3, "d": 1, "e": 0}
sorted(d.items(), key=lambda kv: kv[1])
```

2. `operator.itemgetter`

```{python}
from operator import itemgetter
sorted(d.items(), key=itemgetter(1))
```

3. Get just the sorted list of keys (you could separately use `sorted(d.values())`:

```{python}
sorted(d.keys(), key=d.get)
```

4. Using `zip()`: 
```{python}
sorted(zip(d.values(), d.keys()))
```

My solution is to invert the dictionary (making a list of `(value,key)` tuples), then sort the inverted dictionary.

```{python}
def inv_dict_list(d):
    result = []
    for k in d:
        result.append((d[k],k))
    return(result)
d2 = sorted(inv_dict_list(d))
```

Plotting:

```{python}
## magic unzipping
## https://stackoverflow.com/questions/19339/transpose-unzip-function-inverse-of-zip
d2B = list(zip(*d2))
```

Could also get the separate lists via tuple comprehensions (too magic!) or a good old-fashioned `for` loop ...

```{python}
d2_vals = (x[0] for x in d2)
d2_keys = (x[1] for x in d2)
```

```{python}
import matplotlib.pyplot as plt
## fig, ax = plt.subplots()
plt.barh(left=0,width=d2B[0],bottom=range(len(d2B[0])),height=0.5)
plt.yticks(d2B[0],d2B[1])
plt.show()
```

Might want to try a Python ggplot analogue, e.g. [here](https://towardsdatascience.com/how-to-use-ggplot2-in-python-74ab8adec129) (but [there's no coord_flip avilable](https://stackoverflow.com/questions/42009582/coord-flip-does-not-work)) ? [seaborn](https://seaborn.pydata.org/examples/horizontal_barplot.html)?

