---
title: "math 1mp3 announcements (fall 2019)"
date: "`r format(Sys.time(), '%d %b %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 2   
---

## Week #0

- You should figure out how to start Python (online or on your computer: instructions [here](../notes/use_python.html)) and register for CodeLab (instructions [here](./notes/use_python.html#codelab)) as soon as possible.
- Read the [course outline](./outline.html).
- Tutorials will start on Mon 9 September.
- Classes will be held in TSH B105
    - the first class for section C01 is Tues 3 Sep 4:30
    - the first class for section C02 is Weds 4 Sep 2:30
- Information on HW#1: this can be found on CodeLab, in the table of contents under "Python3 Topics > Assignment #1". It is due before 23:59 on Monday September 16. Please be sure to submit your solutions to these 16 questions before then.  You can get practice with similar questions in the relevant CodeLab subsections (Arithmetic; Strings (I) and (II); Conditions and Branches). All the material you need for these questions is in the Week-1 notes, and will be covered by the end of class next Monday (Sep 9).

## Week #1

- We've set up a Facebook forum for the class at: https://www.facebook.com/groups/406619356725041/ . This forum is available for any course-related questions. Questions about homework are OK, but no spoilers please! Please be polite.
