---
title: "Math 1MP3: Introduction to mathematical and scientific programming<br>Fall 2019"
date: "`r format(Sys.time(), '%d %b %Y')`"
---

## Personnel

- When e-mailing either one of the instructors or the TA about the course, 
    - **Please include "1MP3" in the subject. Include your Mac ID and student ID, and your (lecture and/or tutorial) section in the body of the e-mail**. 
    - Please allow at least one full business day for responses. **We might not answer e-mails sent less than 24hrs before an exam, assignment, or project is due.** The primary time to get help is during tutorials and office hours.
- *Instructors*:
     - Ben Bolker (`bolker@mcmaster.ca`) Office hours TBA, 314 Hamilton Hall; [web page](http://www.math.mcmaster.ca/bolker).
	 - Weijie Pang (`pangw6@mcmaster.ca`).  Office hours TBA, 414 Hamilton Hall.
- *Teaching assistants*: Nik Počuča (`pocucan@mcmaster.ca`) and Steve Cygu (`cygus@mcmaster.ca`), Aghigh Farhadi (marking only).

## Lectures

- C01 (Dr. Bolker) Mon 3:30-4:20, Tues 4:30-5:20, Thurs 3:30-4:20, all in TSH B105
- C02 (Dr. Pang) Mon 2:30-3:20, Weds 2:30-3:20, Fri   4:30-5:20, all in TSH B105

## Tutorials and assignments

- Times and locations:
     - L01 Mo 10.30 11.20 JHE_233A/234 (Steve Cygu)
     - L02 We 12.30 13.20 JHE_233A/234 (Steve Cygu)
     - L05 Mo 12.30 13.20 JHE_233A/234 (Steve Cygu)
     - L03 Mo 09.30 10.20 JHE_233A/234 (Nik Počuča)
     - L04 Tu 11.30 12.20 JHE_233A/234 (Nik Počuča)

- Tutorials will start **Monday 9 September**.  They will be used primarily for help and review, not for presenting new material (any exceptions will be noted). There will be approximately four quizzes over the course of the semester, held during tutorials.
- Some assignments will use [CodeLab](http://www.turingscraft.com/index.php).  Other assignments, approximately weekly, will be submitted in a dropbox on Avenue to Learn (AtL).  You need to register for (and pay for) CodeLab; see instructions [here](https://bbolker.github.io/math1mp/notes/use_python.html#codelab)
- To ensure consistency between sections, assignments will **only** be announced on AtL and on the course web page, not in class.

## Course material

- The course will cover a basic introduction to programming and mathematical/scientific computing in Python.
- The primary course material is the lectures, and associated lecture notes, available at http://bbolker.github.io/math1mp/
  - The **optional** (but recommended) course textbook is Gries et al. *Practical Programming* 3d ed., available from the bookstore or the publisher ([The Pragmatic Bookshelf](https://pragprog.com/book/gwpy3)).
- It is recommended to print the lecture notes and bring them to class to make additional notes
- It will be helpful, but not required, to bring a laptop or tablet to class. It will be helpful to install Python on your computer, following instructions to be provided in lab, but you can also use online Python servers provided.

##  Evaluation

- Assignments (10%)
- Quizzes (5%)
- Final project (5%)
- Midterm tests
     - evening, Tues 22 October (tentative) (20%)
     - evening, Tues 19 November (tentative) (20%)
- Final exam (40%) [to be scheduled by the Registrar]


## Late work and remarking

All assignments are due on Avenue to Learn, unless otherwise stated. We will penalize late work by 25% per day.

Marks can be adjusted in this class. If you follow the correct steps we will be happy to adjust your mark on tests or assignments. If you deviate from the steps they may still adjust them but they will be less **likely** to. :-)

- When you receive your marked test or assignment, go home and look at it carefully. Spend some time going over each mistake and comparing it with the solutions.
- If you are sure that you deserve some extra marks, send the TA an email saying you would like the mark adjusted in one of the tutorials, and **specify** which one. Come early to the tutorial class and they will look over your work.

Here are some **exceptions**.

- If you used pen or marker on your test, you can take it home and have it adjusted at a later date.
- If you use pencil we will not adjust your marks after you have taken your test away. In this case we suggest that you take photos of your work to review and leave the test with a TA; then you can have your mark adjusted later.

# Policies

The instructors reserve the right to change the weightings in the grading scheme. For students in good academic standing, other weights might be considered. In either case, the final mark will be computed using this weighting and the new weighting(s). The highest score for a particular student will be their final mark. At the end of the course the grades may be adjusted but this can only increase your grade and will be done uniformly. We will use the grade equivalence chart published in the Undergraduate Calendar to convert between percentages and letter grades. 

### In case of difficulty/problems

Contact Dr. Bolker or Dr. Pang as soon as possible. Failing that, contact the Associate Dean's Office in BSB 129.

## Dates subject to change

The instructor and university reserve the right to modify elements of the course during the term. The university may change the dates and deadlines for any or all courses in extreme circumstances. If either type of modification becomes necessary, reasonable notice and communication with the students will be given with explanation and the opportunity to comment on changes. It is the responsibility of the student to check their McMaster email and course websites weekly during the term and to note any changes.

## Policy regarding missed work

If you are absent from the university for a minor medical reason, lasting fewer than 3 days, you may report your absence, once per term, without documentation, using the McMaster Student Absence Form. Absences for a longer duration or for other reasons must be reported to your Faculty/Program office, with documentation, and relief from term work may not necessarily be granted. When using the MSAF, report your absence to `bolker@mcmaster.ca`. You must then contact Dr. Bolker immediately (within 2 working days) by email to learn what relief may be granted for the work you have missed, and relevant details such as revised deadlines, or time and location of a make-up exam. Please note that the MSAF may not be used for term work worth 25% or more, nor can it be used for the final examination. Further details can be found here: https://www.mcmaster.ca/msaf/index.html and here: http://academiccalendars.romcmaster.ca/content.php?catoid=13&navoid=2208#Requests_for_Relief_for_Missed_Academic_Term_Work

Should an accommodation for missed work be granted, the percentage for a missed test will be added to your final exam.  The percentage for a missed assignment or quiz will be distributed amongst your remaining assignments or quizzes.

If you must miss a lecture, it is your responsibility to find out what was covered. The best way to do this is to borrow a classmate's notes, read them over, and then ask your instructor if there is something that you do not understand.

Once a final examination is written, the final grade cannot be adjusted to take into account any special situation. For more detail, and to download the "Petition For Missed Term Work Form," visit the "Procedures & Forms" web page  located at the address http://www.science.mcmaster.ca/associatedean/current-students/procedures-forms.html. 

## Online component

We will be using the learning software Avenue to Learn.  Students should be aware that private information such as first and last names, user names for the McMaster e-mail accounts, and program affiliation may be visible to other students in the course. By taking this course you consent to this disclosure. If you have any questions or concerns about this, please discuss them with the course instructor. Grades will be posted on AtL.

## Academic Integrity

The expectations for this class are fairly simple: however, if you have any questions **please ask**. See the McMaster Office of Academic Integrity’s web page for general information.

You are expected to exhibit honesty and use ethical behavior in all aspects of the learning process.  Academic credentials you earn are rooted in principles of honesty and academic integrity. Academic dishonesty &mdash; knowingly acting or failing to act in a way that results or could result in unearned academic credit or advantage &mdash; can result in serious consequences, e.g. the grade of zero on an assignment, loss of credit with a notation on the transcript (notation reads: “Grade of F assigned for academic dishonesty”), and/or suspension or expulsion from the university. It is your responsibility to understand what constitutes academic dishonesty. For information on the various kinds of academic dishonesty please refer to the Academic Integrity Policy, specifically Appendix 3, located at http://www.mcmaster.ca/academicintegrity. The following illustrates only three forms of academic dishonesty: **plagiarism**, e.g. the submission of work that is not your own or for which other credit has been obtained, **improper collaboration in group work**, **copying or using unauthorized aids in tests and examinations**.

- In this course, you are encouraged to discuss the assigned problems with other students in your class. You may *discuss* the solutions to problem sets, but **you must write up your solutions yourself without copying phrasing from other students’ work. If you work with others, you must clearly indicate on your write-up who you worked with.**  You must write the solutions in your own words without referring to any other students' work. The copying of anyone's solutions will be considered academic dishonesty.
- In this course you are not allowed to talk to or communicate in any way (e.g. pass notes) with anyone but the instructors or the invigilators during an examination. You are on your honor to observe any specified time limits and to refrain from communicating with anyone other than the instructors/TAs about the contents of the exam.
- While it is not technically an example of academic dishonesty, *continuing to write once the announcement that the allotted time for a test or examination is over* without the express consent of the instructors or one of the invigilators will be penalized.
 
The instructors and university reserve the right to modify elements of the course during the term.  The university may change the dates and deadlines for any or all courses in extreme circumstances.  If either type of modification becomes necessary, reasonable notice and communication with the students will be given with explanation and the opportunity to comment on changes.  It is the responsibility of the student to check their McMaster email and course websites weekly during the term and to note any changes.

Students who require academic accommodation must contact Student Accessibility Services (SAS) to make arrangements with a Program Coordinator.  Academic accommodations must be arranged for each term of study.  Student Accessibility Services can be contacted by phone 905-525-9140 ext. 28652 or e-mail `sas@mcmaster.ca`.  For further information, consult McMaster University's [Policy for Academic Accommodation of Students with Disabilities](http://www.mcmaster.ca/policy/Students-AcademicStudies/AcademicAccommodation-StudentsWithDisabilities.pdf).

---

This outline will be linked from the course home page. However, it is your responsibility to check the course home page and syllabus regularly for further announcements, course handouts, assigned work and its due dates, information about test dates and locations when this information becomes available, downloadable course related material, etc.. Recorded marks for tests and assignments will be posted on Avenue to Learn. You should check these once they become available and bring any discrepancies to the attention of the instructors or the TA as soon as possible.

---

Materials for this course have been developed over several years by Drs. B. Bolker and M. Valeriote at McMaster University. Most material is available for re-use under a [Creative Commons BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode) license.
