## MATH 1MP, Introduction to mathematical/scientific programming

Revision: `r as.character(Sys.time())`

This is an *approximate* and *preliminary* schedule for the course.  It is guaranteed to change.

### week 1: basics

Notes ([HTML](http://htmlpreview.github.io/?https://github.com/bbolker/math1mp/blob/master/admin/week1.html), [PDF](../notes/week1.pdf))

* M Jan 5  introduction to the course; introduction to [Python](http://xkcd.com/353/); editors and workflows
* W Jan 7  data types; logical operations; string operations; regular expressions
* F Jan 9  lists; indexing and slicing

<!-- editors (xkcd butterfly?) -->
<!-- variable naming and conventions; http://www.gps.alaska.edu/jeff/Classes/GEOS436+636/02_fundamentals.pdf; **assignment**: set up Python and write a couple of trivial programmes -->

### week 2: flow control

* M Jan 12 conditionals, loops
* W Jan 14 flow control; while
* F Jan 16 flow charts

### week 3: debugging etc.

* M Jan 19 [debugging](http://danluu.com/teach-debugging/)
* W Jan 21 testing
* F Jan 23 benchmarking/profiling/optimization: Euclidean algorithm

### week 4: functions and modules

* M Jan 26 functions and scoping
* W Jan 28 importing modules, Roman numeral examples
* F Jan 30 more Roman numeral examples

### week 5: more function examples/reviews

* M Feb 2 function examples
* W Feb 4 ... continued
* F Feb 6 ... continued

### week 6: tuples and dictionaries (and arrays?) (and plotting)

* M Feb 9 tuples and dictionaries 
* W Feb 11 ... more ...
* F Feb 13 **MIDTERM exam** (in class)

**midterm recess: Feb 16-21**

### week 7: random numbers, numeric representations

* M Feb 23 plotting (data visualization)
* W Feb 25 pseudo-random numbers and applications
* F Feb 27 numeric representations

### week 8: floating point and exception handling

* M Mar 2 floating point algorithms (root-finding, optimization)
* W Mar 4 floating point algorithms (differential equations)
* F Mar 6 exception handling

### week 9: data management

* M Mar 9  data management; pandas
* W Mar 11 web scraping
* F Mar 13 databases

### week 10: symbolic computation

* M Mar 16 symbolic computation; SymPy and Sage
* W Mar 18 ... continued
* F Mar 20 ... continued

### week 11 ... projects ...

* M Mar 23  start projects  ...
* W Mar 25
* F Mar 27

### week 12 ... projects ...

* M Mar 30
* W Apr 1

**3 April: Good Friday**

### week 13 ... projects ...
* M Apr 6
* W Apr 8

**8 April: classes end**

