---
title: "final outline"
date: "`r format(Sys.time(), '%H:%M %d %B %Y')`"
author: Ben Bolker
---

You will have 2 hours to complete the final.  It will be cumulative; in particular,
you will be certainly be asked many questions that are similar to those on the midterm,
since these represent the essential basics.

A couple of the questions on the final are modified from [CodingBat](http://codingbat.com), either from the Python section or modified from problems in the Java section.

## Part 1: basics

* atomic variable types (integer, float, string)
* numeric operations (arithmetic, operate-and-modify (`+=`), etc.)
* string operations (adding, splitting, joining)
* data structures: lists, tuples, and dictionaries
    * methods and operators for these types; addition and multiply-by-scalar (for lists and tuples), `.append`, `+=`, `.extend` (for lists), `in` (for all three), value setting (for lists and dictionaries), `.sort()` (for lists)
* mutability	
* slicing and indexing for lists, tuples, and strings
* logical values (`True`, `False`) and logical operators (`or`, `and`, `not`)

## Part 2: flow control

* `if`/`elif`/`else`
* `for` and `while` loops (using `range`, lists, tuples, dictionaries as iterators)
* functions: scope, return values, default and named arguments

## Part 3: examples

You should *understand* these examples: you don't need to be able to re-create them

* Roman numeral translation (both directions)
* bisection search
* numerical integration
* Benford's law

## Part 4: modules

You should be able to *recognize*, *interpret*, and possibly *modify* code from these
modules, but you won't be asked to write any code from scratch.

### `numpy`

* arrays; creation and indexing
* element-wise arithmetic
* `np.linspace`, `np.arange`
* `.shape` attribute

### `matplotlib`

(assuming `import matplotlib.pyplot as plt`)

* setting up plots: `figure`, `add_subplot`
* creating plots: `ax.plot()`, `ax.scatter()`
* plot output: `fig.show()`, `fig.save()`

### `pandas`

* `read_csv()`
* indexing via attribute, `loc`, `iloc`
* `.head()`, `.tail()`
* filtering, using comparison and equality operators and logical operators `&`, `|`, `~`
* `.groupby()` and `.aggregate()`
* `.plot()`
